version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: zip

changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ with .AuthorUsername }} (@{{ . }}){{ end }}"
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "^chore: update$"
      - "^chore: docs$"
      - "^docs: update$"
      - "^chore: schema$"
      - "^chore: typo$"
      - "^chore: auto-update generated files$"
      - "^chore: update schema$"
      - "^chore: schema update$"
      - "^chore\\(deps\\): "
      - "^(build|ci): "
      - "merge conflict"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: jreslock
    name: terraform-provider-docs-local
  draft: true
  prerelease: auto
  mode: replace
  name_template: >-
    {{ if eq .Version "latest" }}{{ .TagName }}{{ else }}v{{ .Version }}{{ end }}
  footer: |
    **Full Changelog**: https://github.com/jreslock/terraform-provider-docs-local/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - name: terraform-provider-docs-local
    repository:
      owner: jreslock
      name: homebrew-tap
      branch: main
    homepage: "https://github.com/jreslock/terraform-provider-docs-local"
    description: "A tool for managing and browsing local copies of Terraform provider documentation"
    license: "MIT"
    test: |
      system "#{bin}/terraform-provider-docs-local --version"
    install: |
      bin.install "terraform-provider-docs-local-darwin-#{Hardware::CPU.arch}" => "terraform-provider-docs-local"
