name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build devcontainer and run checks
        uses: devcontainers/ci@v0.3.1900000417
        with:
          subFolder: ${{ github.workspace }}
          configFile: .devcontainer/CI/devcontainer.json
          runCmd: |
            task pre-commit-run
