name: Pre-Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  pre-release:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for bump label
        id: check_label
        run: |
          echo "Checking for bump label..."
          PATCH=$(echo "${{ toJson(github.event.pull_request.labels) }}" | jq -e '.[].name | test("bump:patch")')
          MINOR=$(echo "${{ toJson(github.event.pull_request.labels) }}" | jq -e '.[].name | test("bump:minor")')
          MAJOR=$(echo "${{ toJson(github.event.pull_request.labels) }}" | jq -e '.[].name | test("bump:major")')
          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"
          if $MAJOR; then
            echo "bump=major" >> $GITHUB_ENV
          elif $MINOR; then
            echo "bump=minor" >> $GITHUB_ENV
          elif $PATCH; then
            echo "bump=patch" >> $GITHUB_ENV
          else
            echo "No bump label found. Skipping workflow."
            exit 0
          fi

      - name: Build devcontainer and generate CHANGELOG.md
        uses: devcontainers/ci@v0.3.1900000417
        with:
          subFolder: ${{ github.workspace }}
          configFile: .devcontainer/CI/devcontainer.json
          runCmd: |
            task bump-${{ env.bump }}
