name: Pre-Release

on:
  pull_request:
    types:
      - closed # Trigger when a PR is merged
  workflow_dispatch: # Allow manual triggering

jobs:
  pre-release:
    if: github.event.pull_request.merged == true # Only run if the PR was merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version bump
        id: version_bump # Add an ID to reference this step
        run: |
          # Default to patch if no label or pattern is found
          VERSION_BUMP="patch"

          # Check PR labels for version bump
          if [[ "${{ github.event.pull_request.labels }}" == *"bump:major"* ]]; then
            VERSION_BUMP="major"
          elif [[ "${{ github.event.pull_request.labels }}" == *"bump:minor"* ]]; then
            VERSION_BUMP="minor"
          fi

          # Output the version bump type
          echo "VERSION_BUMP=$VERSION_BUMP" >> $GITHUB_ENV
          echo "::set-output name=bump::$VERSION_BUMP"

      - name: Build devcontainer and generate CHANGELOG.md
        uses: devcontainers/ci@v0.3.1900000417
        with:
          subFolder: ${{ github.workspace }}
          configFile: .devcontainer/CI/devcontainer.json
          runCmd: |
            task bump-${{ steps.version_bump.outputs.bump }}
