name: Pre-Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
    inputs:
      bump:
        description: 'Bump type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  pre-release:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && contains(join(github.event.pull_request.labels.*.name, ','), 'bump:') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine bump type
        id: determine_bump
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "bump=${{ github.event.inputs.bump }}" >> $GITHUB_OUTPUT
          else
            echo "Checking for bump label..."
            LABELS=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')

            echo "Labels: $LABELS"
            if echo "$LABELS" | grep -q "bump:major"; then
              echo "bump=major" >> $GITHUB_OUTPUT
            elif echo "$LABELS" | grep -q "bump:minor"; then
              echo "bump=minor" >> $GITHUB_OUTPUT
            elif echo "$LABELS" | grep -q "bump:patch"; then
              echo "bump=patch" >> $GITHUB_OUTPUT
            else
              echo "No bump label found. Skipping workflow."
              exit 0
            fi
          fi

      - name: Build devcontainer and generate CHANGELOG.md
        uses: devcontainers/ci@v0.3.1900000417
        with:
          subFolder: ${{ github.workspace }}
          configFile: .devcontainer/CI/devcontainer.json
          runCmd: |
            CURRENT_TAG=$(task get-current-tag | tail -n 1)
            NEXT_TAG=$(task get-next-tag VERSION_TYPE=${{ steps.determine_bump.outputs.bump }} | tail -n 1)
            echo "Bumping version from $CURRENT_TAG to $NEXT_TAG"
            task bump-${{ steps.determine_bump.outputs.bump }}
