name: Pre-Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  pre-release:
    if: >
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'bump:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version bump
        id: version_bump
        run: |
          VERSION_BUMP="patch"
          if [[ "${{ github.event.pull_request.labels }}" == *"bump:major"* ]]; then
            VERSION_BUMP="major"
          elif [[ "${{ github.event.pull_request.labels }}" == *"bump:minor"* ]]; then
            VERSION_BUMP="minor"
          fi
          echo "bump=$VERSION_BUMP" >> $GITHUB_OUTPUT

      - name: Build devcontainer and generate CHANGELOG.md
        uses: devcontainers/ci@v0.3.1900000417
        with:
          subFolder: ${{ github.workspace }}
          configFile: .devcontainer/CI/devcontainer.json
          runCmd: |
            task bump-${{ steps.version_bump.outputs.bump }}
