name: Release

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
  workflow_dispatch:
    inputs:
      snapshot:
        description: 'Create a snapshot release'
        required: false
        default: false
        type: boolean
      bump:
        description: 'Bump type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' ||
      github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine bump type
        id: determine_bump
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "bump=${{ github.event.inputs.bump }}" >> $GITHUB_OUTPUT
          else
            echo "Checking for bump label..."
            LABELS=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r 'map(.name | gsub("'"; "")) | join(",")')

            echo "Labels: $LABELS"
            BUMP_LABELS=$(echo "$LABELS" | grep -oE "bump:(major|minor|patch)" | sort | uniq)
            BUMP_COUNT=$(echo "$BUMP_LABELS" | wc -l)

            if [[ "$BUMP_COUNT" -gt 1 ]]; then
              echo "Error: Multiple bump labels found: $BUMP_LABELS. Please use only one bump label." >&2
              exit 1
            elif [[ "$BUMP_LABELS" == *"bump:major"* ]]; then
              echo "bump=major" >> $GITHUB_OUTPUT
            elif [[ "$BUMP_LABELS" == *"bump:minor"* ]]; then
              echo "bump=minor" >> $GITHUB_OUTPUT
            elif [[ "$BUMP_LABELS" == *"bump:patch"* ]]; then
              echo "bump=patch" >> $GITHUB_OUTPUT
            else
              echo "No bump label found. Skipping workflow."
              exit 0
            fi
          fi

      - name: Get Release Automator App Token
        id: get-token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.RELEASE_AUTOMATOR_GH_APP_ID }}
          private_key: ${{ secrets.RELEASE_AUTOMATOR_GH_APP_PRIVATE_KEY }}

      - name: Generate CHANGELOG.md, bump version, and create release
        id: release
        uses: devcontainers/ci@v0.3.1900000417
        with:
          subFolder: ${{ github.workspace }}
          configFile: .devcontainer/CI/devcontainer.json
          env: |
            GITHUB_TOKEN=${{ steps.get-token.outputs.token }}
          runCmd: |
            task git-safe
            CURRENT_TAG=$(task get-current-tag | tail -n 1)
            NEXT_TAG=$(task get-next-tag VERSION_TYPE=${{ steps.determine_bump.outputs.bump }} | tail -n 1)
            echo "Bumping version from $CURRENT_TAG to $NEXT_TAG"
            task bump-${{ steps.determine_bump.outputs.bump }}
            task build-all
            if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.snapshot }}" = "true" ]; then
              task release-snapshot
            else
              task release
            fi

      - name: Publish Release Artifacts
        id: publish-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            artifacts/*
            dist/*
