name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      snapshot:
        description: 'Create a snapshot release'
        required: false
        default: false
        type: boolean

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up devcontainer
        uses: devcontainers/ci@v0.4.0
        with:
          workspaceFolder: ${{ github.workspace }}
          devcontainerPath: .devcontainer/devcontainer.json

      - name: Build for all platforms
        run: task build-all

      - name: Generate changelog
        if: github.event_name != 'workflow_dispatch' || !github.event.inputs.snapshot
        run: task changelog

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.snapshot }}" = "true" ]; then
            task release-snapshot
          else
            task release
          fi

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            artifacts/*
            dist/*
