name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      snapshot:
        description: 'Create a snapshot release'
        required: false
        default: false
        type: boolean

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build devcontainer and generate release artifacts
        uses: devcontainers/ci@v0.3.1900000417
        with:
          subFolder: ${{ github.workspace }}
          configFile: .devcontainer/CI/devcontainer.json
          runCmd: |
            task build-all
            if [ "${{ github.event_name }}" != "workflow_dispatch" ] || [ "${{ github.event.inputs.snapshot }}" ]; then
              task changelog
            fi
            if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.snapshot }}" = "true" ]; then
              task release-snapshot
            else
              task release
            fi

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            artifacts/*
            dist/*
